name: Test EC2 Connection

on:
  workflow_dispatch:

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Check SSH port
        run: |
          nc -zv 13.60.117.189 22 || echo "Cannot connect to SSH"
