name: Load MySQL Data to Google Sheet

# Trigger schedule: daily at 8 AM BDT (UTC+6 → 02:00 UTC)
on:
  schedule:
    - cron: "30 2 * * *"   # 02:00 UTC = 08:00 BDT
  workflow_dispatch:       # optional: allow manual trigger

jobs:
  load_data:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repo
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas mysql-connector-python gspread oauth2client google-auth

    # Step 4: Run Python script
    - name: Run Python loader
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        SERVICE_ACNT_CRED: ${{ secrets.SERVICE_ACNT_CRED }}   # Google service account JSON
      run: |

        python script.py
