name: Load MySQL Data to Google Sheet_ssh

# Trigger schedule: every 5 minutes (for testing)
on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 min
  workflow_dispatch:       # optional: allow manual trigger

jobs:
  load_data:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repo
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas mysql-connector-python gspread oauth2client google-auth paramiko sshtunnel

    # Step 4: Set up SSH for EC2 connection
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.DB_HOST }} >> ~/.ssh/known_hosts

    # Step 5: Run Python script
    - name: Run Python loader
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        SERVICE_ACNT_CRED: ${{ secrets.SERVICE_ACNT_CRED }}   # Google service account JSON
      run: |
        python script_ssh.py
