name: Run with VPN

on:
  workflow_dispatch:

jobs:
  vpn-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install WireGuard & Python
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard python3 python3-pip

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install mysql-connector-python pandas gspread oauth2client google-auth

      - name: Configure WireGuard
        run: |
          cat <<EOF > wg0.conf
          [Interface]
          PrivateKey = ${{ secrets.WG_PRIVATE_KEY }}
          Address = ${{ secrets.WG_ADDRESS }}
          DNS = 1.1.1.1

          [Peer]
          PublicKey = ${{ secrets.WG_SERVER_PUBLIC_KEY }}
          Endpoint = ${{ secrets.WG_ENDPOINT }}
          AllowedIPs = ${{ secrets.WG_ALLOWED_IPS }}
          PersistentKeepalive = 25
          EOF

      - name: Start WireGuard
        run: |
          sudo wg-quick up ./wg0.conf
          sudo wg

      - name: Force DNS resolution
        run: |
          sudo rm -f /etc/resolv.conf
          echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf
          echo "nameserver 8.8.8.8" | sudo tee -a /etc/resolv.conf
          cat /etc/resolv.conf

      - name: Debug DNS
        run: |
          nslookup oauth2.googleapis.com || true
          ping -c 3 oauth2.googleapis.com || true

      - name: Run Python Script Through VPN
        env:
          SERVICE_ACNT_CRED: ${{ secrets.SERVICE_ACNT_CRED }}
        run: |
          python3 vpn_run_server.py

      - name: Stop WireGuard
        if: always()
        run: |
          sudo wg-quick down ./wg0.conf
